### ISSUE TITLE
rhi.rs panic on linux

### ISSUE THREAD

**Issue by unic0rn9k** [unic0rn9k/office-apocalypse#4]
```
thread 'main' panicked at 'error: fragment shader input `materialId' with explicit location has no matching output
', src/rhi.rs:226:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/core/src/panicking.rs:64:14
   2: office_apocalypse::rhi::Device::new_shader_program
             at ./src/rhi.rs:226:13
   3: office_apocalypse::renderer::Renderer::new
             at ./src/renderer.rs:62:23
   4: office_apocalypse::main
             at ./src/main.rs:49:24
   5: core::ops::function::FnOnce::call_once
             at /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by unic0rn9k** [comment]
Det virker 🎉
